language: python
python:
- '3.6'
install:
- python setup.py install
script:
- python -m unittest discover
deploy:
  provider: pypi
  user: majorov
  password:
    secure: QSTUhetDV25jFPEF0CUQ+obB2hRDgmMQrEgplfE2zUPmB36ntyWDCDkId3/oye5nXYhVRPb2ftSOIq56hqzw8Z1nffGg068+jkFAAbkMy1JjR1jrJJZX0bJ5nSDl2s4ytziXEB6BI2W+b+87Fq7K5xJYCY+PKkkVgRTZxPhzCdDkHYMGIm4ZO0FfRE0R7MaIFUg3Rtzt1WTi8PMZb4pPBV7MK3aV0Dh1C+3/gDkcbBV5T35ZCSMeQ7i+S7wn3JdOj08nW5S3wIatgVmeG07EXpc+7db9grICWaXT4xhLQ+xPV0mCslWbQ2G2kSfwgC1QIu7kp9MSJzN48I6v+2Z3fBvX9ml7fXgKW/4Z1tsp7EX/R/cxa4Z67it7JLnfiNyzpa0FDdZQDCPg/K9xVqplBlqo/Thqj/PNDaX0b0OooAD6WYLecZe/layD7bnotK+UEl/IBMY+noQaml49hfb0LrmYHV7uDbR4Puvv6g9OBmTMH4RT9zSbJfy11r29qXKi0KBNAshbW7AFnFO70tMQ9npd14zRKQPk7lFbjtq9X7kd6mXzYw3TrrVQ/hzuLydIVCey/ar9tZJXxyCen1Xb3IzikmVJkJIiwYSUNK7/xVsVWnGiCEbRR1yxjXOYXT4H/laTNkOiXrifcnawaZdbeh9fpYfgR5eDm0tLg4c3+vE=
  on:
    branch: master
    tags: true
