language: python
python:
- '3.6'
install:
- python setup.py install
script:
- python -m unittest discover
deploy:
  provider: pypi
  user: majorov
  password:
    secure: yfVGdi36LdNOnfebxt1sRlFaFBVzuqC4OCLTfKAZQAffWgpip3HoIcoOebbI8EfWS4Kx1uWI6mR4u0SGFEDx9eBfz2NcIeDAqotSAu1nv0h+Jsb/GYRhFNlGT4t4NzjMNM3ODqJqxY9bTms4hYBUN1qIVoj5ChcH2C9+cjS+U1aqzYYVi+4R6UlfYiGWQDO+bk1BTuJ0g18jg853Zjsx8KgP7BmYNDj40nImNH8keMSBaZv/bHWWG6l2HjBRg6GUrc5TZDC0+2vmAdtbAYAzQhe2nnN7Zr+5AGVrcu2eQueAlbgYJP5X+Cf4a0EERbJ3PUK2mDg78ZV4/zfYvAkUUrPjdcCOGzd/4z4Phxzuc59DqKbKkcu/ciUK+RmvjLGeRTkidp/xGx2eetLpVJbKOFpAAQNumyAOQPdtNmPuRwuGgCUqPgskO0wwbN+N4h0S8VeWMsqD2svOqyShgURDS1sjtFix5cH+G6pmRl7YbE/5i+BF6DndXPv2rwlrWg3bkNLllBheyCh48IwW07wqa5sF6ktohZgJRP2y40PS2A6xwR4zzbc/Z/x0T0LbZDxIfyvIYqVaKRDH/a51lNZ8a028FlpiaOi4p9hWsA9Fo9M9Twil+vTs7GR2dTgjtCnPx/7vHgv+n9jrKSvnIvQs5AGlpDLEF3DipU+p4IyKpag=
  on:
    branch: master
