language: python
python:
- '3.6'
install:
- python setup.py install
script:
- python -m unittest discover
deploy:
  provider: pypi
  user: majorov
  password:
    secure: 1WYQ7UwbrZidbKfPkvQcSl7d1rGZ4QnVL9CuECGnCJNFAz/p8rPLHnGkTkotDQ0MjEdcsnYrXnuEX1YidU0Gr9nzMpQ3W9cX4/XlzpfCGlrtJOSsLC+XTSqGsyLutOI2Ym+TbW6ZKJ/IfoUk5ZHSSctiJEaSCld44i67t6OAxPuQdnjLKCFc48kkNr4dGIP3zmJbD8hJimTPkxm0AXnN00gXFWL+ORzvo91k+ht8wfZG4w7tXk/LVuSRmBQ6DZOX2dI4OtRidsUciTWHg2SrflkIDeOYM+/eabmQ+A5KM60Ld+VYRQpndixzpqyWdIjej6fdaPURQRDmMe5EEIc2j3csLRkAuvVFnUlHUjwUs2KTnLJzSwEJYxBVzbvvz1mUGXNUQlKa22a9VHMTEX1Rt7HhLWXzMVSqAUqx4jR47J3UDojz96kS73/Ovp90cGdnVEz4nBtJ4ibt4eqM6aV8OkJSXATncMMMtkP9jShp02LOYUjLXnKuNaVP6psVXXhvdVbIUwyE9G92/yD4zyBVOlFu4Ie89t6bnlWVGwgwVqtONRJrJxUkMh1d/gQztoEMWs+/jWG2ZviLAFrCcqHJ/YZ0AlfupjnO4+NgtUWMx5W7gApip+hQI3whPrr6fCTaTdI425/SAUdo6/pp/gXLoaOZi0YCuz1kvkgAGCs41kY=
  on:
    branch: master
